public class PDFDataWrapper {
    public String uuid {get;set;}
    public String firstname {get;set;}
    public String lastname {get;set;}
    public Datetime startdatetime {get;set;}
    public Integer numofpers {get;set;}
    public String storename {get;set;}
    public String storestreet {get;set;}
    public String storepostalcode {get;set;}
    public String storecity {get;set;}

    public PDFDataWrapper(){}
}